### PR TITLE
SDK update + fix failing AST transformation for a valid JS file

### LINKED ISSUE #56: Parsing fails on valid JS file
Discovered though https://github.com/bblfsh/javascript-driver/issues/54#issuecomment-462829594

Using latest bblfshd v2.11.6/client.v3/javasript driver v2.6.0 parsing of the valid [2.4 mb .js file](https://github.com/laravel/telescope/blob/6f0a10ec586cfa1a22218b6778bf9c1572b97912/public/app.js) fails.

## Steps to reproduce

```
wget https://raw.githubusercontent.com/laravel/telescope/6f0a10ec586cfa1a22218b6778bf9c1572b97912/public/app.js
node --check app.js // check JS syntax
go install github.com/bblfsh/client-go/cmd/bblfsh-cli/...
bblfsh-cli ./app.js
```

## Expected

Very long semantic UAST printed in YAML format. 

## Actual

```
couldn't parse public/app.js: transform failed: received 15 errors:
	check: key "extra": field was not used: parenthesized
	check: key "extra": field was not used: parenthesized
	check: key "extra": field was not used: parenthesized
	check: key "extra": field was not used: parenthesized
	check: key "extra": field was not used: parenthesized
	check: key "extra": field was not used: parenthesized
	check: key "extra": field was not used: parenthesized
	check: key "extra": field was not used: parenStart
	check: key "extra": field was not used: parenStart
	check: key "extra": field was not used: parenStart
	check: key "extra": field was not used: parenthesized
	check: key "extra": field was not used: parenthesized
	check: key "extra": field was not used: parenthesized
	check: key "extra": field was not used: parenthesized
	check: key "extra": field was not used: parenStart
```

As noted https://github.com/bblfsh/javascript-driver/issues/54#issuecomment-462853077 actual order of the failing Transformations can vary.

### PR DESCRIPTION
**Pull request by bzz**
Update SDK to latest version and verifies that it fixes #56 and #61 

Update:  it does not, 
 - full SDK update scope is in https://github.com/bblfsh/javascript-driver/pull/57#issuecomment-466985496 
 - fix for #56 in 70ce5c1
 - map `JSXIdentifier` to `uast:Identifier` from #58 in f20563e
 - skip mapping function comments 175bec4

### CODE REVIEW

**Comment by bzz** [comment]
CI is failing with latest SDK, presumably due to https://github.com/bblfsh/sdk/pull/356, [logs](https://api.travis-ci.org/v3/job/492309486/log.txt)

**Comment by bzz** [comment]
There are 788 log lines mentioning failing checks, with 7 uniq failures
```
grep -c "check " ci-unused-fields-log.txt
788
grep "check: " ci-unused-fields-log.txt | sort | uniq | wc -l
7
```

Those are
```
check: unused field(s) on node BlockStatement: trailingComments
check: unused field(s) on node Identifier: [optional typeAnnotation]
check: unused field(s) on node Identifier: leadingComments
check: unused field(s) on node Identifier: typeAnnotation
check: unused field(s) on node ImportDefaultSpecifier: leadingComments
check: unused field(s) on node StringLiteral: [leadingComments trailingComments]
check: key "specifiers": key "Node": unused field(s) on node uast:Identifier: @pos
```

**Comment by bzz** [comment]
```
grep -c "check:" ci-unused-fields-log-2.txt
798
grep "check:" ci-unused-fields-log-2.txt| sort | uniq | wc -l
9
```

on the latest master it's 9 failing checks now

```
check: unused field(s) on node BlockStatement: trailingComments
check: unused field(s) on node Identifier: [optional typeAnnotation]
check: unused field(s) on node Identifier: leadingComments
check: unused field(s) on node Identifier: typeAnnotation
check: unused field(s) on node ImportDeclaration: [leadingComments trailingComments]
check: unused field(s) on node ImportDeclaration: leadingComments
check: unused field(s) on node ImportDefaultSpecifier: leadingComments
check: unused field(s) on node StringLiteral: [leadingComments trailingComments]
check: key "specifiers": key "Node": unused field(s) on node uast:Identifier: @pos
```

**Comment by bzz** [comment]
Keeping the comment above updated with the current status

**Comment by bzz** [comment]
All import issues resolved, 3 more `extra` added.

**Comment by bzz** [comment]
Few more fixed and sever new showed up, https://github.com/bblfsh/javascript-driver/pull/57#issuecomment-466985496 scope updated.

To check current status:
```
$ go run vendor/gopkg.in/bblfsh/sdk.v2/cmd/bblfsh-sdk/main.go test 2>&1 | tee log.txt
$ curl -s log.txt | grep "check:" | sort | uniq | wc -l
7
```

**Comment by bzz** [comment]
Just 4 to go :)

**Comment by bzz** [comment]
and CI is green now! 🎉 

Technically, SDK update is finished BUT 3 errors above are a fix for #56 and would have very similar changes so going to take care of them here as well.

**Comment by bzz** [comment]
Done, scope an description updated, everything is ready for review 🚀

File: driver/normalizer/normalizer.go [hunk 1]
```diff
@@ -50,8 +53,11 @@ var Preprocessors = []Mapping{
 	Map(
 		Part("_", Obj{
 			uast.KeyType: String("RegExpLiteral"),
-			"extra": Obj{
-				"raw": Var("raw"),
+			"extra": Fields{
+				{Name: "raw", Op: Var("raw")},
+				//FIXME(bzz): map parenthesis
```
Comment (juanjux) [inline driver/normalizer/normalizer.go]: I don't think we need to map tokens like parenthesis.

File: driver/normalizer/normalizer.go [hunk 2]
```diff
@@ -61,43 +67,46 @@ var Preprocessors = []Mapping{
...
 }
 
 // Normalizers is the main block of normalization rules to convert native AST to semantic UAST.
 var Normalizers = []Mapping{
 	MapSemantic("Identifier", uast.Identifier{}, MapObj(
-		Obj{
-			"name": Var("name"),
+		Fields{
+			{Name: "name", Op: Var("name")},
+			//FIXME(bzz): map Flow variable types properly
```
Comment (dennwc) [inline driver/normalizer/normalizer.go]: Not for this PR, but we can probably move those type annotations into `uast:Argument`'s `Type` field.

File: driver/normalizer/normalizer.go (hunk 1 above)
Comment (dennwc) [reply driver/normalizer/normalizer.go]: Agree with @juanjux, this is merely a TODO. We can add a custom position field into the node and that's it. The priority of this "fix" is very low.

Comment (bzz) [reply driver/normalizer/normalizer.go]: This is good suggestion! It's just that in order for it to be consistent between all drivers, I belive we still need to act up on this change and _at least_ document this approach, so it can be referred/followed in the other drivers.

This is motivation to keep the FIXME and make another pass on all drivers addressing those.

File: driver/normalizer/normalizer.go [hunk 3]
```diff
@@ -212,24 +237,32 @@ var Normalizers = []Mapping{
...
-			"body":      Var("body"),
-			"params": Each("params", Cases("param_case",
+		Fields{
+			{Name: "id", Op: Var("name")},
+			{Name: "generator", Op: Var("gen")}, // FIXME: define channels in SDK? or return a function?
+			{Name: "async", Op: Var("async")},   // TODO: async
+			{Name: "body", Op: Var("body")},
+			//FIXME(bzz): map predicate properly
+			{Name: "predicate", Drop: true, Op: Any()},
+			//FIXME(bzz): map Flow return type annotations
```
Comment (dennwc) [inline driver/normalizer/normalizer.go]: This one may be easy to map to `uast:Function.Returns[0].uast:Argument.Type`. Can be done in a separate PR.

File: driver/normalizer/normalizer.go [hunk 4]
```diff
@@ -212,24 +237,32 @@ var Normalizers = []Mapping{
...
+			{Name: "returnType", Drop: true, Op: Any()},
+			//FIXME(bzz): map Flow argument type annotations
```
Comment (dennwc) [inline driver/normalizer/normalizer.go]: Is this for argument types? Sounds like templates or something.

File: driver/normalizer/normalizer.go [hunk 5]
```diff
@@ -212,24 +237,32 @@ var Normalizers = []Mapping{
...
-			"generator": Var("gen"),   // FIXME: define channels in SDK? or return a function?
-			"async":     Var("async"), // TODO: async
-			"body":      Var("body"),
-			"params": Each("params", Cases("param_case",
+		Fields{
+			{Name: "id", Op: Var("name")},
+			{Name: "generator", Op: Var("gen")}, // FIXME: define channels in SDK? or return a function?
+			{Name: "async", Op: Var("async")},   // TODO: async
+			{Name: "body", Op: Var("body")},
+			//FIXME(bzz): map predicate properly
```
Comment (dennwc) [inline driver/normalizer/normalizer.go]: Can you please describe briefly what it is (if you already know, of course).

File: driver/normalizer/normalizer.go (hunk 1 above)
Comment (bzz) [reply driver/normalizer/normalizer.go]: changed to `TODO`

File: driver/normalizer/normalizer.go (hunk 2 above)
Comment (bzz) [reply driver/normalizer/normalizer.go]: Awesome, thank you for suggestion, moved to https://github.com/bblfsh/javascript-driver/issues/63

File: driver/normalizer/normalizer.go (hunk 3 above)
Comment (bzz) [reply driver/normalizer/normalizer.go]: Thank you for suggestion, moved to https://github.com/bblfsh/javascript-driver/issues/63

**Comment by bzz** [comment]
Thank you for the prompt review, @dennwc @juanjux !

All feedback addressed, scope in PR description updated and only last 3 commits need to be reviewed again.

File: driver/normalizer/normalizer.go (hunk 5 above)
Comment (bzz) [reply driver/normalizer/normalizer.go]: added in a836d36

File: driver/normalizer/normalizer.go (hunk 4 above)
Comment (bzz) [reply driver/normalizer/normalizer.go]: Yes, it's actually for generics support, added more info in a836d36
