### PR TITLE
Bug in handling case of ImportDeclaration

### LINKED ISSUE #70: ImportDeclaration: unhandled case
The file mentioned in #69 also triggers this error if the original issue is fixed:
```
blacklisted nodes of type "ImportDeclaration" (2) found in the tree
```

It's not detected by you test suite and is triggered with this file:

<details>
<summary>jsx.js</summary>

```javascript
// @flow strict
import * as React from "react";
import { graphql, QueryRenderer } from "react-relay";
import Alert from "@kiwicom/orbit-components/lib/Alert";
import InputField from "@kiwicom/orbit-components/lib/InputField";
import type { Environment } from "react-relay";

import environmentReal from "../../services/environment";
import PickerDropDown from "./primitives/PickerDropDown";
import NoResult from "./primitives/NoResult";
import ClickOutside from "../ClickOutside";
import Text from "../Text";
import LocationPickerResultList from "./components/LocationPickerResultList";
import getPlaceholder from "./services/placeholder";
import type { Location } from "../../records/Location";

// FIXME add arrow handling somehow neatly
// const ARROW_UP = 38;
// const ARROW_DOWN = 40;
// const ESC = 27;
// const ENTER = 13;

// FIXME @viktr solve these:
// centralize styles with IataPicker

// FIXME @oreqizer solve these:
// arrow handling

type Props = {|
  value: Location | null,
  onChange: (loc: Location) => void,
  label: string,
  icon: React.Node,
  // defaulted
  environment: Environment,
|};

type State = {|
  active: boolean,
  input: string,
|};

class LocationPicker extends React.Component<Props, State> {
  static defaultProps = {
    environment: environmentReal,
  };

  state = {
    active: false,
    input: "",
  };

  node: { current: any | HTMLDivElement } = React.createRef();

  handleClose = () => {
    this.setState({
      active: false,
    });
  };

  handleSelect = (item: Location) => {
    const { onChange } = this.props;

    onChange(item);
    this.setState({
      active: false,
    });
  };

  handleChange = (ev: SyntheticInputEvent<HTMLInputElement>) => {
    this.setState({
      input: ev.target.value,
      active: true,
    });
  };

  render() {
    const { value, label, icon, environment } = this.props;
    const { active, input } = this.state;

    const placeholder = value ? getPlaceholder(value) : null;

    return (
      <ClickOutside active={active} onClickOutside={this.handleClose}>
        <>
          <InputField
            inlineLabel
            placeholder={placeholder || label}
            onChange={this.handleChange}
            prefix={icon}
            value={active ? input : ""}
          />
          {input && active && (
            <QueryRenderer
              environment={environment}
              query={graphql`
                query LocationPickerQuery($input: String!) {
                  allLocations(last: 50, search: $input) {
                    ...LocationPickerResultList_list
                  }
                }
              `}
              variables={{ input }}
              render={res => {
                if (res.error) {
                  return (
                    <Alert type="critical">
                      <Text t="common.api_error" />
                    </Alert>
                  );
                }

                if (!res.props) {
                  return null;
                }

                if (!res.props.allLocations) {
                  // TODO render this in the list if length is 0
                  return (
                    <NoResult>
                      <Text t="forms.places_no_results" />
                    </NoResult>
                  );
                }

                return (
                  <PickerDropDown ref={this.node}>
                    <LocationPickerResultList
                      list={res.props.allLocations}
                      selectedId={value && value.id}
                      onSelect={this.handleSelect}
                    />
                  </PickerDropDown>
                );
              }}
            />
          )}
        </>
      </ClickOutside>
    );
  }
}

export default LocationPicker;
```

</details>

### PR DESCRIPTION
**Pull request by bzz**
Fixes #70, is triggered by 

```js
import type { Foo } from "bar"
```

that was not properly normalized
 
TODOs
 - [x] 07e7b516ed60003754c7dfb49be18dab8429ef24 added wrong fixtures by mistake.
    This places the right ones for reproducing #69 and #70.
 - [x] fix bug, so ImportDeclaration is mapped 7dd15df

### CODE REVIEW

**Comment by bzz** [comment]
The issue is trigged in `import type` case of this [Flow feature](https://flow.org/blog/2015/02/18/Import-Types/)

**Comment by bzz** [comment]
Rebased on latest master and simples fixture added.

According to our current normalization rules in DSL - everything is supposed to work, but for some reason `ImportDeclacation>"importKind": String("type")` clause does not match, after it's `specifiers` gets replaced from `ImportSpecifier` to `Alias` :/

**Comment by bzz** [comment]
Interesting enough

```js
import type Environment from "react-relay";
```

works as expected - it's the same case of `ImportDeclacation>"importKind": "type"` BUT instead of `ImportSpecifier` it's `ImportDefaultSpecifier` that has no troubles beeing converted to alias WITHOUT `imported: { '@type': "Identifier",` and that gets matched allright

**Comment by bzz** [comment]
Was unbelivably tricky to catch, me and Denys tried several times. 

I belive that happened due to:
 - tooling to test  DSL is getting better (`go test ./driver/`) but no tooling for debugging it yet
 - confusion on the DSL itself: is the sub-tree captured or is it only matched? those cases look the same

File: fixtures/u2_import_subsymbols_namespaced.js.sem.uast [hunk 1]
```diff
@@ -152,6 +152,68 @@
...
+                  line: 3,
+                  col: 1,
+               },
+               end: { '@type': "uast:Position",
+                  offset: 108,
+                  line: 3,
+                  col: 44,
+               },
+            },
+            All: true,
```
Comment (dennwc) [inline fixtures/u2_import_subsymbols_namespaced.js.sem.uast]: This is actually incorrect and was the reason why I think we should rewrite the normalizer for imports.

Still, it may be okay to merge this and then work on a proper fix.

File: fixtures/u2_import_subsymbols_namespaced.js [hunk 2]
```diff
@@ -1,2 +1,3 @@
 import * as namespace from 'file';
 import type File from "file";
+import type Environment from "react-relay";
```
Comment (dennwc) [inline fixtures/u2_import_subsymbols_namespaced.js]: Any reason to add this line? Looks structurally the same as the previous one.

File: fixtures/issue65-op.js [hunk 3]
```diff
@@ -1 +0,0 @@
-var a = 0 + 1;
```
Comment (dennwc) [inline fixtures/issue65-op.js]: Any reason to remove this one?

File: driver/normalizer/normalizer.go [hunk 4]
```diff
@@ -211,7 +210,7 @@ var Normalizers = []Mapping{
 							"Name":      Var("local"),
 							"Node": UASTType(uast.Identifier{}, Obj{
 								uast.KeyPos: Any(),
-								"Name": String("."),
+								"Name": Any(),
```
Comment (dennwc) [inline driver/normalizer/normalizer.go]: FYI it just drops the name of the imported type from an AST.

File: fixtures/issue65-op.js (hunk 3 above)
Comment (bzz) [reply fixtures/issue65-op.js]: This was was recently added by mistake - it was meant only to be part of the local exploration for #65 (which is wontfix)

File: driver/normalizer/normalizer.go (hunk 4 above)
Comment (bzz) [reply driver/normalizer/normalizer.go]: thank you for the heads up! Yup, if left this way for now (which is anyway better then before) it needs to have at least a `TODO`

File: fixtures/u2_import_subsymbols_namespaced.js.sem.uast (hunk 1 above)
Comment (bzz) [reply fixtures/u2_import_subsymbols_namespaced.js.sem.uast]: Thank you for pointing it out - yes, I noticed something fishy is going on with this [All flag](https://godoc.org/gopkg.in/bblfsh/sdk.v2/uast#Import).

Let me look into it again - but in this case, help me understand, you mean that a single type should always be `False`? That way this flag would _only_ be `True` for whiledcard imports. 
Is that correct?

Comment (dennwc) [reply fixtures/u2_import_subsymbols_namespaced.js.sem.uast]: Correct, `All` is true only for wildcards. For this case, it should be false, and `Names` should ideally include the name of the type that is imported.

File: fixtures/u2_import_subsymbols_namespaced.js (hunk 2 above)
Comment (bzz) [reply fixtures/u2_import_subsymbols_namespaced.js]: removed in 7b65c80

File: fixtures/u2_import_subsymbols_namespaced.js.sem.uast (hunk 1 above)
Comment (bzz) [reply fixtures/u2_import_subsymbols_namespaced.js.sem.uast]: added as TODO in 7b65c80

File: driver/normalizer/normalizer.go (hunk 4 above)
Comment (bzz) [reply driver/normalizer/normalizer.go]: added in 7b65c80

**Comment by bzz** [comment]
@dennwc feedback addressed and ready for another round.

I would say we should continue fixing bugs that fail the parsing first, make a release and then get back to improving depth/quality from TODOs.
