### PR TITLE
Handle quoting U+0000 properly

### LINKED ISSUE #62: Parsing fails on valid JS: string
Parsing `string.js` file with content

```js
var escSlash = '\0SLASH'+Math.random()+'\0';
var escOpen = '\0OPEN'+Math.random()+'\0';
var escClose = '\0CLOSE'+Math.random()+'\0';
var escComma = '\0COMMA'+Math.random()+'\0';
var escPeriod = '\0PERIOD'+Math.random()+'\0';
```

results in 

```
 check: key "value": invalid syntax
 check: key "value": invalid syntax ('\0')
 check: key "value": invalid syntax
 check: key "value": invalid syntax ('\0SLASH')
 check: key "value": invalid syntax
 check: key "value": invalid syntax ('\0OPEN')
 check: key "value": invalid syntax
 check: key "value": invalid syntax ('\0')
 check: key "value": invalid syntax
 check: key "value": invalid syntax ('\0CLOSE')
 check: key "value": invalid syntax
 check: key "value": invalid syntax ('\0')
 check: key "value": invalid syntax
 check: key "value": invalid syntax ('\0COMMA')
 check: key "value": invalid syntax
 check: key "value": invalid syntax ('\0')
 check: key "value": invalid syntax
 check: key "value": invalid syntax ('\0')
 check: key "value": invalid syntax
 check: key "value": invalid syntax ('\0PERIOD')
```

Found though #54 

## Steps to reproduce
```
$ bblfsh-cli string.js
```

### PR DESCRIPTION
**Pull request by bzz**
Fixes #62 

TODOs
 - [x] add high-level fixtures to reproduce #62 
 - [x] add low-level unit test to reproduce the cause - `strconv_test.go`
 - [x] make `TestUnquoteSingle` pass:
         modify `unquoteSingle`, so `\0` is handled like escape sequence, resulting in `U+0000`
 - [x] make `TestUnquoteSingleAndQuoteBack` pass:
        ~modify `quoteSingle` so `U+0000` is handled like in JS and results in `\0` (instead of Go `\x00`)~
        That is not possible as right now we are loosing information of the type of escape sequence being used in JS (`\000`, `\x00`, and `\0` - all end up quoted back in Hex format)
         Instead, test fixtures are update to use this canonical form.

### CODE REVIEW

File: driver/normalizer/strconv.go [hunk 1]
```diff
@@ -11,6 +11,7 @@ import (
 
 // unquoteSingle is the same as strconv.Unquote, but uses ' as a quote.
 func unquoteSingle(s string) (string, error) {
+	s = s[1 : len(s)-1]
```
Comment (dennwc) [inline driver/normalizer/strconv.go]: length checks? checks that those trimmed chars are correct quotes?

File: driver/normalizer/strconv_test.go [hunk 2]
```diff
@@ -0,0 +1,41 @@
+package normalizer
+
+import (
+	"testing"
+
+	"github.com/stretchr/testify/require"
+)
+
+func TestUnquoteSingle_NullGo(t *testing.T) {
```
Comment (dennwc) [inline driver/normalizer/strconv_test.go]: I would rather propose a single table test here, instead of multiple identical tests

File: driver/normalizer/strconv.go (hunk 1 above)
Comment (bzz) [reply driver/normalizer/strconv.go]: so far this is just a refactoring - this code was moved from the client of this method in Op impl.
So nothing changed yet.

But I know what you mean :) will try to follow exactly the same logic as is in `strconv.Unquote`

File: driver/normalizer/strconv_test.go (hunk 2 above)
Comment (bzz) [reply driver/normalizer/strconv_test.go]: addressed in 9799217d7f5ec25b70f4db299048a94c488da6c0

File: driver/normalizer/strconv.go (hunk 1 above)
Comment (bzz) [reply driver/normalizer/strconv.go]: addressed in 7d784b9be3628f8b3cc68a6e1cd34d6c495c31be

**Comment by bzz** [comment]
Perf test for comparison of 2 impl of unquoting `\0` by replacing it with `\x00`
```
go test -bench=. ./driver/normalizer
goos: darwin
goarch: amd64
pkg: github.com/bblfsh/javascript-driver/driver/normalizer
BenchmarkReplacingNullEscape_Iterative-4   	 5000000	       303 ns/op	      80 B/op	       2 allocs/op
BenchmarkReplacingNullEscape_Regexp-4      	 1000000	      1089 ns/op	     168 B/op	       7 allocs/op
PASS
ok  	github.com/bblfsh/javascript-driver/driver/normalizer	2.977s
```

**Comment by bzz** [comment]
WIP, but is already open for a feedback

File: driver/normalizer/strconv.go [hunk 3]
```diff
@@ -1,18 +1,43 @@
...
 )
 
 // Functions below are copied from strconv.Unquote and strconv.Quote.
 // Original functions are unable to escape/unescape values containing
 // multiple characters since in Go single quotes represent a rune literal
+// https://github.com/golang/go/blob/65a54aef5bedbf8035a465d12ad54783fb81e957/src/strconv/quote.go#L360
 
 // unquoteSingle is the same as strconv.Unquote, but uses ' as a quote.
 func unquoteSingle(s string) (string, error) {
+	n := len(s)
```
Comment (creachadair) [inline driver/normalizer/strconv.go]: I think this might be clearer as:

```go
if len(s) < 2 || s[0] != s[len(s)-1] {
   return "", strconv.ErrSyntax
}
s = s[0:len(s)-1]
```

It echoes the `len` call, but at least to my eyes, the labor of pulling it out doesn't really help legibility any, and the compiler can be trusted.

Comment (creachadair) [reply driver/normalizer/strconv.go]: Separately: I would probably not re-use `strconv.ErrSyntax` unless the goal is to be plug-compatible with the existing strconv method for some other reason. I think we did so by default when we cloned the code, but generally it's better to avoid re-using another package's errors unless they are designed for that purpose (the main example I can think of is `io.EOF`).

File: driver/normalizer/strconv.go [hunk 4]
```diff
@@ -29,15 +54,59 @@ func unquoteSingle(s string) (string, error) {
 	return string(buf), nil
 }
 
+// contains reports whether the string contains the byte c.
```
Comment (creachadair) [inline driver/normalizer/strconv.go]: ≡`strings.IndexByte(s, c)`

File: driver/normalizer/strconv.go [hunk 5]
```diff
@@ -29,15 +54,59 @@ func unquoteSingle(s string) (string, error) {
...
+	for i := 0; i < len(s); i++ {
+		if s[i] == c {
+			return true
+		}
+	}
+	return false
+}
+
+// replaceEscapedMaybe returns a copy of s with "\\old[^0-9]" replaced by new.
+func replaceEscapedMaybe(s string, old, new rune) string {
```
Comment (creachadair) [inline driver/normalizer/strconv.go]: Is this logic borrowed from a library function somewhere? If so, can you please mention that in the comment?

(And if not I'm going to look at it much more closely, as it is very fiddly)

File: driver/normalizer/strconv.go (hunk 3 above)
Comment (bzz) [reply driver/normalizer/strconv.go]: > I think this might be clearer as:
> 
> ```go
> if len(s) < 2 || s[0] != s[len(s)-1] {
>    return "", strconv.ErrSyntax
> }
> s = s[0:len(s)-1]
> ```
> 
> It echoes the `len` call, but at least to my eyes, the labor of pulling it out doesn't really help legibility any, and the compiler can be trusted.

This makes sense, but for the sake of simplifying future maintenance I would rather keep the current version, that is, as noted in comments a copy of https://golang.org/src/strconv/quote.go?s=9955:9993#L347 (sans not re-using `ErrSyntax`)

File: driver/normalizer/strconv.go (hunk 5 above)
Comment (bzz) [reply driver/normalizer/strconv.go]: It is not - this is a custom implementation of looking ahead 2 runes after `\` with additional new tests.

File: driver/normalizer/strconv.go (hunk 3 above)
Comment (creachadair) [reply driver/normalizer/strconv.go]: Is our intent to preserve patches from upstream in this code? It doesn't seem like that's a good maintenance strategy. Unless we are aiming to eventually replace this with a real library function, I would not recommend trying to maintain similarity simply for its own sake.

That said: This particular example is not a crucial point. I only want to point out that the value in keeping the code similar to its origin is only really useful if we intend to keep them in sync, and that seems like a bigger issue.

File: driver/normalizer/strconv.go (hunk 4 above)
Comment (bzz) [reply driver/normalizer/strconv.go]: addressed in 631f385

File: driver/normalizer/strconv.go [hunk 6]
```diff
@@ -29,15 +54,59 @@ func unquoteSingle(s string) (string, error) {
...
+	var runeTmp [utf8.UTFMax]byte
+	n := utf8.EncodeRune(runeTmp[:], new)
+
+	lastCp := 0
```
Comment (creachadair) [inline driver/normalizer/strconv.go]: Could this be simplified to something like the following (untested):

```go
i := 0
needle := "\\" + old
for i < len(s) {
   next := strings.Index(s[i:], needle)
   if next < 0 {
      break
   }
   // decode the first rune in s[i+next:] to verify it is not [0-9]
   i += next + runeSize
}
```

I think that would be slightly easier to follow than the very careful dance with indices.

File: driver/normalizer/strconv.go (hunk 3 above)
Comment (bzz) [reply driver/normalizer/strconv.go]: > Separately: I would probably not re-use `strconv.ErrSyntax` unless the goal is to be plug-compatible with the existing strconv method for some other reason. I think we did so by default when we cloned the code, but generally it's better to avoid re-using another package's errors unless they are designed for that purpose (the main example I can think of is `io.EOF`).

addressed in ea68ea3

File: driver/normalizer/strconv.go (hunk 6 above)
Comment (creachadair) [reply driver/normalizer/strconv.go]: Separately, is this test actually correct? If a string contains, for example, `\u0000123` that is a valid encoding of [0, 49, 50, 51]. So I think checking for a non-digit after the escape may not be right: `\u` consumes 4 digits and `\U` consumes 8, unconditionally. 

And if this is really _only_ to handle the degenerate case of `\0`, can we specialize it to that instead of making a generic function that has to be so careful about lengths?

Comment (bzz) [reply driver/normalizer/strconv.go]: > Separately, is this test actually correct?
I'm not sure if I understood the question right, but I have tried to add such test in fc24125ac5fe37c1e4c1c41321dbf6d9d01d3f58 and it passes with the current algorithm.

If that does not answer the question - could you please provide another possible input/output that would highlight the issue you see?

Comment (bzz) [reply driver/normalizer/strconv.go]: On https://github.com/bblfsh/javascript-driver/pull/64#discussion_r264402621
> Could this be simplified to something like the following (untested):

I belive it can, although it's not a single-pass algorithm any more.

Not sure if that would be a great simplification - having 1 loop instead of 3 is indeed easier to follow, but one would still need a `buf` to copy memory and some state like `lastCp` that would track parts before the `needle` that are already transferred to `buf`, right?

Or do you suggest some other way to replace the `needle` with `new` rune ? Sorry if I misunderstood the suggestion somehow.

Comment (creachadair) [reply driver/normalizer/strconv.go]: Sorry for the confusion.

It is still single-pass, one pass over the input, assembling the output. I just think that the code here right now is overly micro-optimized for no clear need. Here is how I would simplify it:

```go
func replaceEscapedMaybe(s string, old, repl string) string {
	var out strings.Builder
	for s != "" {
		pos := strings.Index(s, old)
		if pos < 0 {
			break
		}
		out.WriteString(s[:pos])
		s = s[pos+len(old):]
		r, n := utf8.DecodeRuneInString(s)
		s = s[n:]
		if r >= '0' && r <= '9' {
			out.WriteString(old)
		} else {
			out.WriteString(repl)
		}
		if n != 0 {
			out.WriteRune(r)
		}

	}
	out.WriteString(s)
	return out.String()
}
```

There are two key points here: One is that we don't need any rune to string conversions, since this function is only ever called with fixed arguments so we can make them strings. The other is that instead of manually attempting to guess how the allocation should work, we're relying on a well-tested library component (the builder) to handle allocations for us. I did not benchmark this, but I would be very surprised if it's not at least as good. And the difference is not causing us a problem, as far as I can tell.

Comment (creachadair) [reply driver/normalizer/strconv.go]: Note too that this simplifies the logic for the degenerate case where there are no escapes: In that case, it fails the first index probe and returns the entire string. No more special case!

Comment (bzz) [reply driver/normalizer/strconv.go]: Here are the updated benchmarks

```
goos: darwin
goarch: amd64
pkg: github.com/bblfsh/javascript-driver/driver/normalizer
BenchmarkReplacingNullEscape_Iterative-4   	10000000	       192 ns/op	      48 B/op	       2 allocs/op
BenchmarkReplacingNullEscape_Regexp-4      	 2000000	       891 ns/op	     120 B/op	       6 allocs/op
BenchmarkReplacingNullEscape_Simple-4      	10000000	       157 ns/op	      24 B/op	       2 allocs/op
PASS
ok  	github.com/bblfsh/javascript-driver/driver/normalizer	6.576s
```

It is not just simple, but even a bit faster! 👏

**Comment by bzz** [comment]
Here are the updated benchmark, including simpler impl suggested in https://github.com/bblfsh/javascript-driver/pull/64#discussion_r264715909


```
goos: darwin
goarch: amd64
pkg: github.com/bblfsh/javascript-driver/driver/normalizer
BenchmarkReplacingNullEscape_Iterative-4   	 2000000	       745 ns/op	     144 B/op	       8 allocs/op
BenchmarkReplacingNullEscape_Regexp-4      	  500000	      3334 ns/op	     480 B/op	      27 allocs/op
BenchmarkReplacingNullEscape_Simple-4      	 2000000	       633 ns/op	     112 B/op	       9 allocs/op
PASS
ok  	github.com/bblfsh/javascript-driver/driver/normalizer	5.897s
```

It is not just simpler, but is even a bit faster! 👏

File: driver/normalizer/strconv.go (hunk 6 above)
Comment (bzz) [reply driver/normalizer/strconv.go]: Thank you very much for your kind explanation @creachadair, all points make perfect sense! 
Switched to your strings-based implementation in 8c08ccf and benchmark posted in https://github.com/bblfsh/javascript-driver/pull/64#issuecomment-472095705

**Comment by bzz** [comment]
All feedback addressed, ready for another round.

File: driver/normalizer/strconv.go [hunk 7]
```diff
@@ -1,18 +1,44 @@
...
+		return "", fmt.Errorf("%+q does not begin and end with a quote", s)
+	}
+	s = s[1 : len(s)-1]
+
+	if contains(s, '\n') {
+		return "", fmt.Errorf("%+q contains EOL", s)
+	}
+
+	// Is it trivial? Avoid allocation.
+	if !contains(s, '\\') && !contains(s, quote) {
```
Comment (creachadair) [inline driver/normalizer/strconv.go]: I think we can drop the `contains(s, '\\')` call, since it is already handled efficiently by `replaceEscapedMaybe` and saves us an iteration over the string.

Alternatively, maybe consider `if !strings.ContainsAny(s, "\\"+quote) {` which will reduce the test to one iteration.

File: driver/normalizer/strconv.go [hunk 8]
```diff
@@ -1,18 +1,44 @@
...
+		r, size := utf8.DecodeRuneInString(s)
+		if size == len(s) && (r != utf8.RuneError || size != 1) {
+			return s, nil
+		}
+	}
+	s = replaceEscapedMaybe(s, "\\0", "\x00") // treatment of special JS escape seq
+
 	var runeTmp [utf8.UTFMax]byte
-	buf := make([]byte, 0, 3*len(s)/2)
+	buf := make([]byte, 0, 3*len(s)/2) // Try to avoid more allocations.
```
Comment (creachadair) [inline driver/normalizer/strconv.go]: I'm not convinced this is worth the cost, but if we do want to micro-optimize here, I'd assert we should not guess but should instead count the escapes on the way past:

```go
nesc := strings.Count(s, "\\")
if nesc == 0 && !strings.Contains(s, quote) {
   …
}
buf := make([]byte, 0, len(s)+3*nesc/2
```

or words to that effect. Otherwise we are allocating a potentially large buffer to no real purpose given that escapes should be expected to be rare.

File: driver/normalizer/strconv.go [hunk 9]
```diff
@@ -29,15 +55,46 @@ func unquoteSingle(s string) (string, error) {
 	return string(buf), nil
 }
 
+// contains reports whether the string contains the byte c.
+func contains(s string, c byte) bool {
+	return strings.IndexByte(s, c) >= 0
+}
+
+// replaceEscapedMaybe returns a copy of s with "\\old[^0-9]" replaced by new.
```
Comment (creachadair) [inline driver/normalizer/strconv.go]:
```suggestion
// replaceEscapedMaybe returns a copy of s in which occurrences of old followed by a 
// non-digit are replaced by repl.
```

File: driver/normalizer/strconv.go (hunk 8 above)
Comment (bzz) [reply driver/normalizer/strconv.go]: This and above is direct copy from stdlib, no changes :/ 

Just noticed that https://github.com/bblfsh/javascript-driver/pull/64#discussion_r264401155 was somehow lost, so answering here

So far, in my experience maintaining this code - it was _SO much easier_ when the copy is as close as possible to original for 2 reasons:
 - pieces that are copy are clearly identifiable as possible
 - we potentially would need to keep this in sync and eventually just to move to the better version of this in strdlib (e.g grpc has to do the same, as they have special requirements on unquoting for compatibility with c)

So I would suggest keeping it that way for those reason.

In any case - this PR does not change that code/logic, only adds a comment copied from upstream, so I do not think it's that useful to increase the scope of this work by replacing it with some custom logic (given that it delays a release of the driver with a lot of bugs fixed).

But please, let me know if you have strong opinion on that, and we can keep improving this.

File: driver/normalizer/strconv.go (hunk 7 above)
Comment (bzz) [reply driver/normalizer/strconv.go]: Again - this is a copy from stdlib.

`replaceEscapedMaybe` only handled the JS escape sequence and this is fast path for cases when the whole string has nothing to unquote.

Removing this shortcut would not affect the correctness, but it just follows the logic of https://github.com/bblfsh/javascript-driver/pull/64#discussion_r265019605

File: driver/normalizer/strconv.go (hunk 8 above)
Comment (creachadair) [reply driver/normalizer/strconv.go]: That all makes sense. I don't feel strongly that we have to change it.

File: driver/normalizer/strconv_test.go [hunk 10]
```diff
@@ -0,0 +1,139 @@
...
+	{`'\0something\0'`, "\u0000something\u0000", "'\\x00something\\x00'"},
+	{`'\0something\0else'`, "\u0000something\u0000else", "'\\x00something\\x00else'"},
+	{"'\u0000123\\0s'", "\u0000123\u0000s", "'\\x00123\\x00s'"},
+}
+
+func TestUnquoteSingle(t *testing.T) {
+	for i, test := range testCasesUnquote {
+		s, err := unquoteSingle(test.quoted)
+		require.NoError(t, err, msg, i)
+
```
Comment (creachadair) [inline driver/normalizer/strconv_test.go]:
```suggestion
```

File: driver/normalizer/strconv_test.go [hunk 11]
```diff
@@ -0,0 +1,139 @@
...
+	t.Logf("\n\tactual: len=%d", len(actual))
+	for _, c := range actual {
+		t.Logf("%x - %#U", c, c)
+	}
+}
+
+func BenchmarkReplacingNullEscape_Iterative(b *testing.B) {
+	b.ReportAllocs()
+	for n := 0; n < b.N; n++ {
+		for _, test := range testCasesUnquote {
```
Comment (dennwc) [inline driver/normalizer/strconv_test.go]: It should be the opposite: first the loop on test cases, each calls `b.Run`, and inside each one there is a loop on `b.N`.

File: driver/normalizer/strconv_test.go [hunk 12]
```diff
@@ -0,0 +1,139 @@
...
+		if test.canonicalQuoted != "" {
+			assertEquals(t, test.canonicalQuoted, q, i)
+		} else {
+			assertEquals(t, test.quoted, q, i)
+		}
+	}
+}
+
+func assertEquals(t *testing.T, quoted, actual string, i int) {
+	success := assert.Equal(t, quoted, actual, msg, i)
```
Comment (creachadair) [inline driver/normalizer/strconv_test.go]:
```suggestion
	if !assert.Equal(t, quoted, actual, msg, i) {
```

File: driver/normalizer/strconv_test.go [hunk 13]
```diff
@@ -0,0 +1,139 @@
...
+	if !success {
```
Comment (creachadair) [inline driver/normalizer/strconv_test.go]:
```suggestion
```

File: driver/normalizer/strconv_test.go [hunk 14]
```diff
@@ -0,0 +1,139 @@
...
+		printDebug(t, quoted, actual)
+		t.FailNow()
+	}
+}
+
+func printDebug(t *testing.T, quoted, actual string) {
+	t.Logf("\texepcted: len=%d", len(quoted))
```
Comment (creachadair) [inline driver/normalizer/strconv_test.go]:
```suggestion
	t.Logf("\texpected: len=%d", len(quoted))
```

File: driver/normalizer/strconv_test.go [hunk 15]
```diff
@@ -0,0 +1,139 @@
...
+func BenchmarkReplacingNullEscape_Iterative(b *testing.B) {
+	b.ReportAllocs()
+	for n := 0; n < b.N; n++ {
+		for _, test := range testCasesUnquote {
+			replaceEscapedMaybeIter(test.quoted, '0', '\x00')
+		}
+	}
+}
+
+func replaceEscapedMaybeIter(s string, old, new rune) string {
```
Comment (creachadair) [inline driver/normalizer/strconv_test.go]: I think we needn't keep the benchmarks for the previous implementation or the regexp experiment.

Comment (dennwc) [inline driver/normalizer/strconv_test.go]: This function doesn't look trivial. Can you please add a comment for it? Is it in the test file only to compare performance?

File: driver/normalizer/strconv_test.go (hunk 11 above)
Comment (bzz) [reply driver/normalizer/strconv_test.go]: Could you please also explain why? 

This benchmark is supposed to test avg performance on multiple test cases, not to track individual test case performance, thus the order.

File: driver/normalizer/strconv_test.go [hunk 16]
```diff
@@ -0,0 +1,139 @@
...
+var testCasesUnquote = []struct {
+	quoted   string
+	unquoted string
+	// isn't empty only for cases where quote(unqote(s)) != s
+	// e.g when we loose the informaiton wich original escape sequence was used
+	// Golang unquote() defaults to hex format, so it's used as canonical one.
+	canonicalQuoted string
+}{
+	{"'a'", "a", ""},
+	{"'\\x00'", "\u0000", ""},
```
[the remark this answers is not in the document]
Comment (bzz) [reply driver/normalizer/strconv_test.go]: It's intentionally that way here, to communicate/attract attention of the reader that both ways are expected to work.

File: driver/normalizer/strconv_test.go (hunk 15 above)
Comment (bzz) [reply driver/normalizer/strconv_test.go]: It makes me sad, loosing information that way: this clearly communicates that multiple implementations were considered and tested, they also can be removed subsequently instead of maintenance, to avoid the burden.

This effectively makes it const nothing to keep those tests, if it's clearly marked as test-only.

Or am I missing something here?

Comment (bzz) [reply driver/normalizer/strconv_test.go]: addressed in 8659709

Comment (creachadair) [reply driver/normalizer/strconv_test.go]: I understand where you're coming from, but I think it isn't a good idea to keep around experiments in the main code or tests for a package. that doesn't mean it's not useful or interesting, just that it's not relevant to anyone except us.

Fortunately, I don't think anything has to be lost—we could put them into a separate package in a subdirectory, so that someone running tests or benchmarks for this package doesn't pick up a bunch of experiments that aren't relevant to the current implementation. As someone who uses the tests for a package as a primary mechanism for understanding how it works, my own preference is to have a clear separation of "production" from "experiments".

For the reader, if we want to say we tried various things we could just as well put in a comment with the benchmark results: "We tested regexp replacement and manual expansion against the current implementation and found this was fastest".

So: I don't think it needs deleted entirely, but I do think it shouldn't live here.

File: driver/normalizer/strconv_test.go (hunk 14 above)
Comment (bzz) [reply driver/normalizer/strconv_test.go]: addressed in 8659709

File: driver/normalizer/strconv_test.go (hunk 13 above)
Comment (bzz) [reply driver/normalizer/strconv_test.go]: addressed in 8659709

File: driver/normalizer/strconv_test.go (hunk 12 above)
Comment (bzz) [reply driver/normalizer/strconv_test.go]: addressed in 8659709

File: driver/normalizer/strconv_test.go (hunk 10 above)
Comment (bzz) [reply driver/normalizer/strconv_test.go]: addressed in 8659709

File: driver/normalizer/strconv_test.go [hunk 17]
```diff
@@ -0,0 +1,139 @@
...
+	"github.com/stretchr/testify/require"
+)
+
+const msg = "test case %d failed"
+
+var testCasesUnquote = []struct {
+	quoted   string
+	unquoted string
+	// isn't empty only for cases where quote(unqote(s)) != s
+	// e.g when we loose the informaiton wich original escape sequence was used
```
[the remark this answers is not in the document]
Comment (bzz) [reply driver/normalizer/strconv_test.go]: addressed in 8659709

File: driver/normalizer/strconv_test.go [hunk 18]
```diff
@@ -0,0 +1,139 @@
...
+	"github.com/stretchr/testify/assert"
+	"github.com/stretchr/testify/require"
+)
+
+const msg = "test case %d failed"
+
+var testCasesUnquote = []struct {
+	quoted   string
+	unquoted string
+	// isn't empty only for cases where quote(unqote(s)) != s
```
[the remark this answers is not in the document]
Comment (bzz) [reply driver/normalizer/strconv_test.go]: addressed in 8659709 - could you please check again and let me know if it's any better now? Thanks!

File: driver/normalizer/strconv.go [hunk 19]
```diff
@@ -29,15 +55,47 @@ func unquoteSingle(s string) (string, error) {
...
+	}
+	out.WriteString(s)
+	return out.String()
+}
+
 const lowerhex = "0123456789abcdef"
 
 // quoteSingle is the same as strconv.Quote, but uses ' as a quote.
+// quoteSingle(unquoteSingle(s)) may not result in exact same bytes as s,
+// due to quoteSingle always opting in for hex escape sequnece format.
```
[the remark this answers is not in the document]
Comment (bzz) [reply driver/normalizer/strconv.go]: addressed in 8659709

File: driver/normalizer/strconv_test.go [hunk 20]
```diff
@@ -0,0 +1,139 @@
...
+	{`'\0something\0else'`, "\u0000something\u0000else", "'\\x00something\\x00else'"},
+	{"'\u0000123\\0s'", "\u0000123\u0000s", "'\\x00123\\x00s'"},
+}
+
+func TestUnquoteSingle(t *testing.T) {
+	for i, test := range testCasesUnquote {
+		s, err := unquoteSingle(test.quoted)
+		require.NoError(t, err, msg, i)
+
+		require.Equal(t, test.unquoted, s, msg, i)
```
[the remark this answers is not in the document]
Comment (bzz) [reply driver/normalizer/strconv_test.go]: addressed in 5c5255c, thank you for the pro-tip!

File: driver/normalizer/strconv_test.go (hunk 11 above)
Comment (bzz) [reply driver/normalizer/strconv_test.go]: Before
```
BenchmarkReplacingNullEscape_Iterative-4   	 2000000	       754 ns/op	     144 B/op	       8 allocs/op
BenchmarkReplacingNullEscape_Regexp-4      	  500000	      3332 ns/op	     480 B/op	      27 allocs/op
BenchmarkReplacingNullEscape_Simple-4      	 2000000	       648 ns/op	     112 B/op	       9 allocs/op
```

After

```
BenchmarkReplacingNullEscape_Iterative-4   	 2000000	       723 ns/op	     146 B/op	       8 allocs/op
BenchmarkReplacingNullEscape_Regexp-4      	  500000	      3933 ns/op	     480 B/op	      27 allocs/op
BenchmarkReplacingNullEscape_Simple-4      	 2000000	       673 ns/op	     112 B/op	       9 allocs/op
```

Addressed in 3f8805029ce51ccdd4ee62e8932f8874853aedd9 but I would still appreciate small rationale for why it's better @dennwc

File: driver/normalizer/strconv_test.go (hunk 15 above)
Comment (bzz) [reply driver/normalizer/strconv_test.go]: Thank you for explanation, @creachadair that makes sense.

I was missing the perspective of using package API surface as a communication tool for the state of public production VS internal experiments.

> Fortunately, I don't think anything has to be lost

indeed. And another way that may work for this case - is to have it in SVC history.

Updated in 9085daba243ab77d428c35a5a16d0a7d3a8dd148

File: driver/normalizer/strconv_test.go (hunk 16 above)
[the remark this answers is not in the document]
Comment (bzz) [reply driver/normalizer/strconv_test.go]: addressed in bfd8c9b

**Comment by bzz** [comment]
@creachadair @dennwc thank you very much for thorough and prompt reviews! All feedback addressed, ready for another round.

File: driver/normalizer/strconv_test.go [hunk 21]
```diff
@@ -0,0 +1,78 @@
...
+	"testing"
+
+	"github.com/stretchr/testify/assert"
+	"github.com/stretchr/testify/require"
+)
+
+var testCasesUnquote = []struct {
+	quoted   string
+	unquoted string
+	// If this is non-empty it means that quoteing back unqoted string does not
```
Comment (creachadair) [inline driver/normalizer/strconv_test.go]: This helps, thanks, I think I understand better now. With that in mind, I would like to suggest a further clarification (which you should feel free to ignore if it's wrong):

```go
// In some cases unquoting and then re-quoting a quoted string does not produce a
// string that is bitwise identical to the original, even though they denote the same bytes.
// This can happen, for example, if we switch between hex and octal encoding of a byte.
// Test cases where this happens should set canonicalUnquoted to a non-empty string that 
// that decodes via Go's native rules to the byte sequence we want.
// Otherwise (if canonicalUnquoted == "") the test assumes the encoding should round-trip.
```

What do you think?

Comment (creachadair) [reply driver/normalizer/strconv_test.go]: Makes me wonder if we shouldn't just include this in _all_ the test cases just for symmetry—even the ones where it's not strictly necessary.

Comment (bzz) [reply driver/normalizer/strconv_test.go]: Sounds much better to me 🎉 And that also would simplify the test logic.
Addressed in 7f92d74

File: driver/normalizer/strconv_test.go [hunk 22]
```diff
@@ -0,0 +1,75 @@
...
+	t.Logf("\n\tactual: len=%d", len(actual))
+	for _, c := range actual {
+		t.Logf("%x - %#U", c, c)
+	}
+}
+
+func BenchmarkReplacingNullEscape(b *testing.B) {
+	b.ReportAllocs()
+	for _, test := range testCasesUnquote {
+		for n := 0; n < b.N; n++ {
```
Comment (dennwc) [inline driver/normalizer/strconv_test.go]: `b.Run` is missing, similar to tests

Comment (bzz) [reply driver/normalizer/strconv_test.go]: addressed in e7a074f

File: driver/normalizer/strconv_test.go (hunk 11 above)
Comment (bzz) [reply driver/normalizer/strconv_test.go]: Ah! Only with this + https://github.com/bblfsh/javascript-driver/pull/64#discussion_r265256526 I realized what you meant in here.

Avg performance was totally ok for this case as well, but now it's broken down by individual test case.

Thank you!

**Comment by bzz** [comment]
🎉 merging as soon as CI is green
